AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-test-bucket-1689763516

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Address-1689763516
      AttributeDefinitions:
        - AttributeName: AddressId
          AttributeType: N
      KeySchema:
        - AttributeName: AddressId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  S3Handler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: S3CreationHandler
      CodeUri: s3://lambda-test-bucket-12-07-2023/app.zip
      Handler: com.aws.lambda.S3Handler
      Runtime: java11
      Description: Java function
      Role: arn:aws:iam::607695928816:role/Lambda-S3-Event
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: MyS3Bucket     # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix      # or "prefix"
                    Value: .csv      # The value to search for in the S3 object key names

  DestinationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DynamoDBInsertionHandler
      CodeUri: s3://lambda-test-bucket-12-07-2023/app.zip
      Handler: com.aws.lambda.DestinationLambda
      Runtime: java11
      Description: Java function
      Role: arn:aws:iam::607695928816:role/lambda-dynamodb-read-access
      MemorySize: 512
      Timeout: 30
      Tracing: Active

  DestinationLambdaGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref DestinationLambda]]
      RetentionInDays: 3

  S3HandlerGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref S3Handler]]
      RetentionInDays: 3



